CREATE DATABASE movieworld;
USE movieworld;

CREATE TABLE movies (
   id  varchar(12) NOT NULL,
   title varchar(45) NOT NULL,
   director varchar(45) NOT NULL,
   actors varchar(255) NOT NULL,
   release_year int(11) NOT NULL,
   genere varchar(45) NOT NULL,
   rating float,
   story_line varchar(4000) NOT NULL,
   coverimage varchar(12) NOT NULL
);

CREATE TABLE series (
   id  varchar(12) NOT NULL,
   title varchar(45) NOT NULL,
   creator varchar(45) NOT NULL,
   actors varchar(255) NOT NULL,
   release_year int(11) NOT NULL,
   genere varchar(45) NOT NULL,
   rating float,
   story_line varchar(4000) NOT NULL,
   coverimage varchar(12) NOT NULL
);



INSERT INTO movies (id,title,director,actors,release_year,genere,rating,story_line,coverimage) VALUES
    ('MoDT001','The Shawshank Redemption', 'Frank Darabont','Morgan Freeman',1994,'Drama', 9.3,'Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man" unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.','mov1.jpg'),
    ('MoDT002','The Godfather', 'Francis Ford Coppola','Al Pacino', 1972,'Drama', 9.2,'The Godfather "Don" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter" wedding. Michael, Vito" youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don" influence for the same, Vito refuses to do it. What follows is a clash between Vito" fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.','mov2.jpg'),
    ('MoDT003','The Dark Knight', 'Christopher Nolan','Christian Bale', 2008,'Action', 9.0,'Set within a year after the events of Batman Begins (2005), Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as "The Joker" appears in Gotham, creating a new wave of chaos. Batman" struggle against The Joker becomes deeply personal, forcing him to "confront everything he believes" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent, and Rachel Dawes.','mov3.jpg'),
    ('MoDT004','American Psycho', 'Mary Haron','Christian Bale', 2000,'Horror', 7.6,'It" the late 1980s. Twenty-seven year old Wall Streeter Patrick Bateman travels among a closed network of the proverbial beautiful people, that closed network in only they able to allow others like themselves in in a feeling of superiority. Patrick has a routinized morning regimen to maintain his appearance of attractiveness and fitness. He, like those in his network, are vain, narcissistic, egomaniacal and competitive, always having to one up everyone else in that presentation of oneself, but he, unlike the others, realizes that, for himself, all of these are masks to hide what is truly underneath, someone/something inhuman in nature. In other words, he is comprised of a shell resembling a human that contains only greed and disgust, greed in wanting what others may have, and disgust for those who do not meet his expectations and for himself in not being the first or the best. That disgust ends up manifesting itself in wanting to rid the world of those people, he not seeing them as people but only of those characteristics he wants to rid.','mov4.jpg'),
    ('MoDT005','Forest Gump', 'Robert Zemeckis','Tom Hanks', 1994,'Drama', 8.8,'Forrest Gump is a simple man with a low I.Q. but good intentions. He is running through childhood with his best and only friend Jenny. His "mama" teaches him the ways of life and leaves him to choose his destiny. Forrest joins the army for service in Vietnam, finding new friends called Dan and Bubba, he wins medals, creates a famous shrimp fishing fleet, inspires people to jog, starts a ping-pong craze, creates the smiley, writes bumper stickers and songs, donates to people and meets the president several times. However, this is all irrelevant to Forrest who can only think of his childhood sweetheart Jenny Curran, who has messed up her life. Although in the end all he wants to prove is that anyone can love anyone.','mov5.jpg'),
    ('MoDT006','The Hunger Games', 'Gary Ross','Jennifer Lawrence', 2012,'Action', 7.2,'In a dystopian future, the totalitarian nation of Panem is divided into 12 districts and the Capitol. Each year two young representatives from each district are selected by lottery to participate in The Hunger Games. Part entertainment, part brutal retribution for a past rebellion, the televised games are broadcast throughout Panem. The 24 participants are forced to eliminate their competitors while the citizens of Panem are required to watch. When 16-year-old Katniss" young sister, Prim, is selected as District 12"s female representative, Katniss volunteers to take her place. She and her male counterpart, Peeta, are pitted against bigger, stronger representatives, some of whom have trained for this their whole lives.','mov6.jpg'),
    ('MoDT007','Taxi Driver', 'Martin Scorsese','Robert De Niro', 1976,'Drama', 8.2,'Travis Bickle is an ex-Marine and Vietnam War veteran living in New York City. As he suffers from insomnia, he spends his time working as a taxi driver at night, watching porn movies at seedy cinemas during the day, or thinking about how the world, New York in particular, has deteriorated into a cesspool. He" a loner who has strong opinions about what is right and wrong with mankind. For him, the one bright spot in New York humanity is Betsy, a worker on the presidential nomination campaign of Senator Charles Palantine. He becomes obsessed with her. After an incident with her, he believes he has to do whatever he needs to make the world a better place in his opinion. One of his priorities is to be the savior for Iris, a twelve-year-old runaway and prostitute who he believes wants out of the profession and under the thumb of her pimp and lover Matthew.','mov7.jpg'),
    ('MoDT008','Titanic', 'James Cameron','Leonardo DiCaprio', 1997,'Romance', 7.9,'84 years later, a 100 year-old woman named Rose DeWitt Bukater tells the story to her granddaughter Lizzy Calvert, Brock Lovett, Lewis Bodine, Bobby Buell and Anatoly Mikailavich on the Keldysh about her life set in April 10th 1912, on a ship called Titanic when young Rose boards the departing ship with the upper-class passengers and her mother, Ruth DeWitt Bukater, and her fiancé, Caledon Hockley. Meanwhile, a drifter and artist named Jack Dawson and his best friend Fabrizio De Rossi win third-class tickets to the ship in a game. And she explains the whole story from departure until the death of Titanic on its first and last voyage April 15th, 1912 at 2:20 in the morning.','mov8.jpg'),
    ('MoDT009','Red Sparrow', 'Francis Lawrence','Jennifer Lawrence', 2018,'Thriller', 6.6,'A young Russian intelligence officer is assigned to seduce a first-tour CIA agent who handles the CIA" most sensitive penetration of Russian intelligence. The two young officers collide in a charged atmosphere of trade-craft, deception, and inevitably forbidden passion that threatens not just their lives but the lives of others as well.','mov9.jpg'),
    ('MoDT010','Inception', 'Christopher Nolan','Leonardo DiCaprio', 2010,'Science Fiction', 8.8,'Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb" rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible, inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea, but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming.','mov10.jpg'),
    ('MoDT011','Spiderman', 'Jon Watts','Tom Holand', 2019,'Action', 7.4,'A young Peter Parker/Spider-Man begins to navigate his newfound identity as web-slinging superhero Spider-Man. Thrilled by his experience with the Avengers, Peter returns home, where he lives with his Aunt May, under the watchful eye of his new mentor Tony Stark. Peter tries to fall back into his normal daily routine--distracted by thoughts of proving himself to be more than just your friendly neighborhood Spider-Man--but when the Vulture emerges as a new villain, everything that Peter holds most important will be threatened.','mov11.jpg'),
    ('MoDT012','Black Adam', 'Jaume Collet-Serra','The Rock', 2022,'Action', 6.3,'Reawakening after 5000 years, Black Adam becomes the world" ruthless protector: an anti-villain to take on the likes of Superman and Wonder Woman. Now in the 21st-Century, Black Adam must face off against the Justice Society of America and its heroes: Doctor Fate, Hawkman, Atom Smasher and Cyclone. The fate of the world hangs in the balance.','mov12.jpg');


INSERT INTO series (id,title,creator,actors,release_year,genere,rating,story_line,coverimage) VALUES
    ('MoDT013','Breaking Bad', 'Vince Gilligan','Bryan Cranston',2008,'Drama',  9.5,'Walter H. White is a chemistry genius, but works as a chemistry teacher in an Albequerque, New Mexico high school. His life drastically changes when he" diagnosed with stage III terminal lung cancer, and given a short amount of time left to live: a mere matter of months. To ensure his handicapped son and his pregnant wife have a financial future, Walt uses his chemistry background to create and sell the world" finest crystal methamphetamine. To sell his signature "blue meth," he teams up with Jesse Pinkman, a former student of his. The meth makes them very rich very quickly, but it attracts the attention of his DEA brother in law Hank. As Walt and Jesse" status in the drug world escalates, Walt becomes a dangerous criminal and Jesse becomes a hot-headed salesman. Hank is always hot on his tail, and it forces Walt to come up with new ways to cover his tracks.','ser1.jpg'),
    ('MoDT014','Game of Thrones', 'David Benioff, D.B. Weiss','Emilia Clarke', 2011,'Drama', 9.3,'In the mythical continent of Westeros, several powerful families fight for control of the Seven Kingdoms. As conflict erupts in the kingdoms of men, an ancient enemy rises once again to threaten them all. Meanwhile, the last heirs of a recently usurped dynasty plot to take back their homeland from across the Narrow Sea.','ser2.jpg'),
    ('MoDT015','Stranger Things', 'The Duffer Brothers','Millie Bobby Brown', 2016,'Science Fiction', 8.8,'In a small town where everyone knows everyone, a peculiar incident starts a chain of events that leads to a child" disappearance, which begins to tear at the fabric of an otherwise-peaceful community. Dark government agencies and seemingly malevolent supernatural forces converge on the town, while a few of the locals begin to understand that more is going on than meets the eye.','ser3.jpg'),
    ('MoDT016','Money Heist', 'Alex Pina','Ursula Corbero', 2017,'Thriller', 8.2,'To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion memorizing every step, every detail, every probability culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.','ser4.jpg'),
    ('MoDT017','Mr. Robot', 'Sam Esmail','Rami Malek', 2015,'Drama', 8.5,'Elliot is a brilliant introverted young programmer who works as a cyber-security engineer by day and vigilante hacker by night. He also happens to be suffering from a strange condition similar to schizophrenia which he futilely tries to keep under control by regularly taking both legal and illegal drugs and visiting his therapist. When a strange feisty young woman named Darlene and a secretive middle-aged man calling himself Mr. Robot, who claims to be the mysterious leader of an underground hacking group known as F-Society, offer Elliot a chance to take his vigilantism to the next level and help them take down E-Corp, the corrupt multi-national financial company that Elliot works for and likes to call Evil Corp, Elliot finds himself at the crossroads. Mr. Robot, who has personal reasons for wanting to take down E-Corp, also reveals that he already has one ally, an even more mysterious, secretive and highly dangerous shadowy hacking group known only as Dark Army. Meanwhile, Elliot" childhood and only friend, Angela, who blames E-Corp for the death of their parents, tries to take down E-Corp legally by joining their ranks and trying to dig up evidence of their corruption from the inside. A wild card in this scheme becomes Tyrell Wellick, an unhinged psychopathic E-Corp yuppie, originally from Scandinavia, who has a very unusual relationship with his dominant and ambitious wife Joanna. After many twists and turns, Mr. Robot" plan is finally put in motion - with catastrophic (un)intended results. But that" just the end of the beginning of the real story.','ser5.jpg'),
    ('MoDT018','The Boys', 'Seth Rogen','Antony Starr', 2016,'Action', 8.8,'"The Boys" is set in a universe in which superpowered people are recognized as heroes by the general public and owned by a powerful corporation, Vought International, which ensures that they are aggressively marketed and monetized. Outside of their heroic personas, most are arrogant and corrupt. The series primarily focuses on two groups: the titular Boys, vigilantes looking to keep the corrupted heroes under control, and the Seven, Vought International" premier superhero team. The Boys are led by Billy Butcher, who despises all superpowered people, and the Seven are led by the egotistical and unstable Homelander. As a conflict ensues between the two groups, the series also follows the new members of each team: Hugh "Hughie" Campbell of the Boys, who joins the vigilantes after his girlfriend is killed in a high-speed collision by the Seven" A-Train, and Annie January/Starlight of the Seven, a hopeful young heroine forced to face the truth about the heroes she admires.','ser6.jpg'),
    ('MoDT019','Hunters', 'David Weil','Al Pacino', 2020,'Crime', 7.2,'In 1977 New York City, a troubled young Jewish man bent on revenge is taken in by a secret group of Nazi hunters fighting a clandestine war against the cabal of high-ranking Nazi officials in hiding who work to create the Fourth Reich.','ser7.jpg'),
    ('MoDT020','You Dont Know Jack' , 'Barry Levinson','Al Pacino', 2010,'Drama', 7.6,'Dr. Jack Kevorkian (1928 - 2011 ) in the 1990s, when he defies Michigan law assisting the suicide of terminally-ill persons. Support comes from his sister, a lab tech, the Hemlock Society president, and a lawyer. The child of survivors of the Armenian genocide interviews applicants: his sister video tapes them. He assembles a device allowing a person to initiate a three-chemical intravenous drip. The local D.A., the governor, and the Legislature respond. In court scenes, Kevorkian is sometimes antic. He" single-minded about giving dying individuals the right to determine how their lives will end. He wants the Supreme Court to rule. He picks a fight he can" win: is it hubris or heroism?','ser8.jpg'),
    ('MoDT021','The Queens Gambit', 'Scott Frank','Anya Taylor-Joy', 2020,'Drama', 8.6,'Nine year-old orphan Beth Harmon is quiet, sullen, and by all appearances unremarkable. That is, until she plays her first game of chess. Her senses grow sharper, her thinking clearer, and for the first time in her life she feels herself fully in control. By the age of sixteen, she" competing for the U.S. Open championship. But as Beth hones her skills on the professional circuit, the stakes get higher, her isolation grows more frightening, and the thought of escape becomes all the more tempting. Based on the book by Walter Tevis.','ser9.jpg'),
    ('MoDT022','Better Call Saul', 'Vince Gilligan','Bob Odenkirk', 2015,'Drama', 8.9,'Before Saul Goodman, he was Jimmy McGill. And if you"e calling Jimmy, you"e in real trouble. The prequel to "Breaking Bad" follows small-time attorney, Jimmy McGill, as he transforms into Walter White" morally challenged lawyer, Saul Goodman.','ser10.jpg'),
    ('MoDT023','Friends', 'Marta Kauffman','Jennifer Aniston', 1994,'Comedy', 8.9,'Ross Geller, Rachel Green, Monica Geller, Joey Tribbiani, Chandler Bing, and Phoebe Buffay are six twenty-somethings living in New York City. Over the course of 10 years and seasons, these friends go through life lessons, family, love, drama, friendship, and comedy.','ser11.jpg');
